import { vars } from "nativewind";

export const themes = {
  default: {
    light: vars({
      "--background": "#fcfcfc",
      "--foreground": "#171717",
      "--border": "#dfdfdf",
      "--input": "#f6f6f6",
      "--ring": "#79e6a8",
      "--primary": "#79e6a8",
      "--primary-foreground": "#1e2723",
      "--secondary": "#fdfdfd",
      "--secondary-foreground": "#171717",
      "--destructive": "#ce2914",
      "--destructive-foreground": "#fffcfc",
      "--muted": "#ededed",
      "--muted-foreground": "#202020",
      "--accent": "#ededed",
      "--accent-foreground": "#202020",
      "--popover": "#fcfcfc",
      "--popover-foreground": "#525252",
    }),
    dark: vars({
      "--background": "#121212",
      "--foreground": "#e2e8f0",
      "--border": "#292929",
      "--input": "#242424",
      "--ring": "#4ade80",
      "--primary": "#006231",
      "--primary-foreground": "#dae6e2",
      "--secondary": "#242424",
      "--secondary-foreground": "#fafafa",
      "--destructive": "#54160e",
      "--destructive-foreground": "#eaa99f",
      "--muted": "#1f1f1f",
      "--muted-foreground": "#a2a2a2",
      "--accent": "#313131",
      "--accent-foreground": "#fafafa",
      "--popover": "#242424",
      "--popover-foreground": "#a9a9a9",
    }),
  },
};
